version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4.13
    restart: always
    ports:
      - "8123:8123" # HTTP-порт для запросов к ClickHouse
      - "9000:9000" # Native-порт для запросов к ClickHouse
    env_file:
      - .env
    networks:
      - clickhouse-network

networks:
  clickhouse-network:
    driver: bridge

